spring:
  config:
    import:
      - classpath:application-smtp.yml
      - classpath:application-secrets.yml
      - classpath:application-datasource.yml
      - classpath:application-statistics.yml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_size: 999
        show_sql: true
        format_sql: true
        use-new-id-generator-mappings: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

semester:
  current: 2024-1
