spring:
  secret-key: ENC(3Axy90/Q9qcGhITAhLe3szCYR4f/+Y2tHg+wB9LT0rKY4vA93dOOXS5C8y5cRpQW86qgkZHxdObgVukID7m54c2DkHWYaP1vhJx4UGQ8vE4iYGhavkeVIVnGNgdQJaTUj5txPV+Megc=)

jwt:
  access-duration: ENC(tD3DYlWXy3EFdJsV8Kxt0w==)
  refresh-duration: ENC(kBIFdFZUPPiHoYf9+ygd+sQdspaEslFc)

jasypt:
  password: ${JASYPT_PASSWORD}

