spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(zXSG4UQSImGJO43kfByhu1puU+EJCvOuNuHKDmfmS+igKL5UFduySInn4zAsQInKVSUBOKtI8zbXGARYxBU4qzap07SNz2M9Hx9AKChL9AokGj4L4AEdy5WHJx3uTCEojDbiXf8eFIOUtNPpX5r7hxfHbgQJcOpBZbLs+cXrYdYKmCuWJIgXOg==)
    username: ENC(vK26Q95U2gok8SniTtcRJw==)
    password: ENC(TdeTq+JiuNzk82zm4LlhoeTvWidVQfLPAEVhopseT/s=)

server:
  port: 8080
  domain: ENC(0mRFnCrUEeChBPYQxQzxhS7wGsqeTHQgij8ihMSZxps=)

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(6efWN1cjJeIKNMcuOHpkv6O/WMTwJAdYKtPUjVedkuBV4RhYELgJYNQ6yOPfI3U40WML38a75Uo0J+UD19p71RmF2+BOkbMx4H2pQSOxRjaXTWr6ZQi6RkWQWZ9bZHam9Hl1yc6RmJBn9c7obQbwJJSzAujjcWTqFi3fZ93wdWcLQIwir27W5b6BEiGTjoOd)
    username: ENC(vK26Q95U2gok8SniTtcRJw==)
    password: ENC(rAOJqzq+OtNaSc3ldWKv+1OZvnIJ4oJpaYB0/dZCZ4Q=)

server:
  port: 8090
  domain: ENC(nWjqzyqSvWGy4zsGHk/mjEy9QlmqQ20OpBmTqqmaKPI2f7HurQxmRg==)

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/suwiki
    username: ${db.username:root}
    password: ${db.password:password}

server:
  port: 8080
  domain: http://localhost:8080

---

spring:
  config:
    activate:
      on-profile: h2

  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        # todo: 예약어 수정 후 삭제
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    open-in-view: false

---

spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    url: jdbc:mysql://localhost:3306/suwiki-test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.username:root}
    password: ${db.password:112233}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
